spring.application.name=${APP_NAME:TakeHomeChallenge}

# ==========================================
# Data base - PostgreSQL
# ==========================================
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mi_base_db}
spring.datasource.username=${JDBC_DATABASE_USERNAME:root}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
# ==========================================
# Server
# ==========================================
server.port=${SERVER_PORT:8080}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/}

# ==========================================
# SpringDoc OpenAPI / Swagger
# ==========================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.generate-ddl=${JPA_GENERATE_DDL:true}
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# Logging
# ==========================================
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.com.example=${LOGGING_LEVEL_COM_EXAMPLE:DEBUG}



# ==========================================
# Manager error
# ===========================================
app.exception-handler.enabled=true
